package com.momenta.dao.impl;
import com.momenta.dao.ExpenseDAO; import com.momenta.database.DatabaseConnection; import com.momenta.model.Expense;
import java.sql.*; import java.util.*;
public class ExpenseDAOImpl implements ExpenseDAO{
 public Expense save(Expense e){String s="INSERT INTO expenses(user_id,amount,category,note,expense_date) VALUES(?,?,?,?,?)";try(PreparedStatement p=DatabaseConnection.getConnection().prepareStatement(s,Statement.RETURN_GENERATED_KEYS)){p.setInt(1,e.getUserId());p.setDouble(2,e.getAmount());p.setString(3,e.getCategory());p.setString(4,e.getNote());p.setString(5,e.getExpenseDate());p.executeUpdate();try(ResultSet r=p.getGeneratedKeys()){if(r.next())e.setId(r.getInt(1));}return e;}catch(SQLException x){throw new RuntimeException("Failed to save expense",x);}}
 public void update(Expense e){String s="UPDATE expenses SET amount=?,category=?,note=?,expense_date=? WHERE id=? AND user_id=?";try(PreparedStatement p=DatabaseConnection.getConnection().prepareStatement(s)){p.setDouble(1,e.getAmount());p.setString(2,e.getCategory());p.setString(3,e.getNote());p.setString(4,e.getExpenseDate());p.setInt(5,e.getId());p.setInt(6,e.getUserId());p.executeUpdate();}catch(SQLException x){throw new RuntimeException("Failed to update expense",x);}}
 public void delete(int id){try(PreparedStatement p=DatabaseConnection.getConnection().prepareStatement("DELETE FROM expenses WHERE id=?")){p.setInt(1,id);p.executeUpdate();}catch(SQLException x){throw new RuntimeException("Failed to delete expense",x);}}
 public List<Expense> findAll(int userId){List<Expense> l=new ArrayList<>();try(PreparedStatement p=DatabaseConnection.getConnection().prepareStatement("SELECT * FROM expenses WHERE user_id=? ORDER BY expense_date DESC,id DESC")){p.setInt(1,userId);try(ResultSet r=p.executeQuery()){while(r.next()){Expense e=new Expense();e.setId(r.getInt("id"));e.setUserId(r.getInt("user_id"));e.setAmount(r.getDouble("amount"));e.setCategory(r.getString("category"));e.setNote(r.getString("note"));e.setExpenseDate(r.getString("expense_date"));l.add(e);}}return l;}catch(SQLException x){throw new RuntimeException("Failed to load expenses",x);}}
}
