package com.momenta.dao.impl;
import com.momenta.dao.IncomeDAO; import com.momenta.database.DatabaseConnection; import com.momenta.model.Income;
import java.sql.*; import java.util.*;
public class IncomeDAOImpl implements IncomeDAO{
 public Income save(Income i){String s="INSERT INTO income(user_id,amount,source,income_date) VALUES(?,?,?,?)";try(PreparedStatement p=DatabaseConnection.getConnection().prepareStatement(s,Statement.RETURN_GENERATED_KEYS)){p.setInt(1,i.getUserId());p.setDouble(2,i.getAmount());p.setString(3,i.getSource());p.setString(4,i.getIncomeDate());p.executeUpdate();try(ResultSet r=p.getGeneratedKeys()){if(r.next())i.setId(r.getInt(1));}return i;}catch(SQLException x){throw new RuntimeException("Failed to save income",x);}}
 public void update(Income i){String s="UPDATE income SET amount=?,source=?,income_date=? WHERE id=? AND user_id=?";try(PreparedStatement p=DatabaseConnection.getConnection().prepareStatement(s)){p.setDouble(1,i.getAmount());p.setString(2,i.getSource());p.setString(3,i.getIncomeDate());p.setInt(4,i.getId());p.setInt(5,i.getUserId());p.executeUpdate();}catch(SQLException x){throw new RuntimeException("Failed to update income",x);}}
 public void delete(int id){try(PreparedStatement p=DatabaseConnection.getConnection().prepareStatement("DELETE FROM income WHERE id=?")){p.setInt(1,id);p.executeUpdate();}catch(SQLException x){throw new RuntimeException("Failed to delete income",x);}}
 public List<Income> findAll(int userId){List<Income> l=new ArrayList<>();try(PreparedStatement p=DatabaseConnection.getConnection().prepareStatement("SELECT * FROM income WHERE user_id=? ORDER BY income_date DESC,id DESC")){p.setInt(1,userId);try(ResultSet r=p.executeQuery()){while(r.next()){Income i=new Income();i.setId(r.getInt("id"));i.setUserId(r.getInt("user_id"));i.setAmount(r.getDouble("amount"));i.setSource(r.getString("source"));i.setIncomeDate(r.getString("income_date"));l.add(i);}}return l;}catch(SQLException x){throw new RuntimeException("Failed to load income",x);}}
}
